# ============================================================================
# Notebook: nod_final_map_countries
# Language: R
# Key: nod_final_map_countries
# Generated: 2026-08-01T15:16:49.391Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-08-01T05:44:06.340Z ───────────────────────────────────
# Generate map with countries and fixed aspect ratio
# Propósito: Generate suitability map with Peru, Ecuador, and Colombia geopolitical borders clipped to raster extent, shifted barrier labels, and fixed coordinate aspect ratio using coord_sf
# Artifacts: #3632
# runtime: modal:sdm-r
# duration_ms: 17233
# lastEditedAt: 2026-08-01T15:16:49.391Z
# lastEditSource: figure_editor

library(terra)
library(sf)
library(ggplot2)
library(ggrepel)
library(geodata)

message("Loading previously clipped raster and occurrences...")
r_mask <- rast("o5_clipped_suitability.tif")
r_df <- as.data.frame(r_mask, xy = TRUE, na.rm = TRUE)
colnames(r_df)[3] <- "Suitability"

occs <- read.csv("o1_occs_clean.csv")
lon_col <- grep("lon", names(occs), ignore.case = TRUE, value = TRUE)[1]
lat_col <- grep("lat", names(occs), ignore.case = TRUE, value = TRUE)[1]

# Define the bounding box from the raster to clip the countries and prevent zoom-out
bbox_raster <- st_bbox(c(xmin = xmin(r_mask), xmax = xmax(r_mask), 
                         ymin = ymin(r_mask), ymax = ymax(r_mask)), 
                       crs = st_crs(4326))
bbox_polygon <- st_as_sfc(bbox_raster)

message("Loading country borders (Peru, Ecuador, Colombia)...")
# Download GADM data for the three countries (level 0 = country borders)
per <- gadm(country = "PER", level = 0, path = tempdir())
ecu <- gadm(country = "ECU", level = 0, path = tempdir())
col <- gadm(country = "COL", level = 0, path = tempdir())

# Combine and convert to sf
countries <- rbind(per, ecu, col)
countries_sf <- st_as_sf(countries)

# Clip countries to the raster's extent so the plot doesn't zoom out
message("Clipping country borders to the raster extent...")
countries_clipped <- st_intersection(countries_sf, bbox_polygon)

message("Preparing barriers...")
# We already unzipped this in the previous step, but let's be safe
if (!dir.exists("barriers_shp")) unzip("barriers_sobralia_turkeliae.zip", exdir = "barriers_shp")
barriers_file <- list.files("barriers_shp", pattern = "\\.shp$", full.names = TRUE)[1]
barriers <- st_read(barriers_file, quiet = TRUE)
barriers <- st_transform(barriers, 4326)

barrier_col <- grep("barrier", names(barriers), ignore.case = TRUE, value = TRUE)[1]

# Calculate centroids for placing labels
barriers_centers <- suppressWarnings(st_centroid(barriers))
coords <- st_coordinates(barriers_centers)
barriers_centers$X <- coords[, "X"]
barriers_centers$Y <- coords[, "Y"]

message("Generating map with fixed coordinates, countries, and shifted labels...")
p <- ggplot() +
  # Suitability raster
  geom_raster(data = r_df, aes(x = x, y = y, fill = Suitability)) +
  scale_fill_distiller(palette = "Spectral", direction = -1,
                       name = "Habitat\nSuitability",
                       guide = guide_colorbar(barwidth = 1.5, barheight = 12,
                                              frame.colour = "black", ticks.colour = "black")) +
  # Geopolitical country borders (clipped)
  geom_sf(data = countries_clipped, fill = NA, color = "#474747", linewidth = 0.4) +
  # Barriers
  geom_sf(data = barriers, aes(linetype = .data[[barrier_col]]), 
          color = "black", linewidth = 0.8) +
  scale_linetype_discrete(name = "Barriers") +
  # Barrier labels (shifted to the right using nudge_x)
  geom_text_repel(data = barriers_centers, 
                  aes(x = X, y = Y, label = .data[[barrier_col]]),
                  fontface = "bold", size = 4.5, 
                  bg.color = "white", bg.r = 0.15, 
                  segment.color = "black", min.segment.length = 0,
                  nudge_x = 2, direction = "y", hjust = 0) +
  # Presences
  geom_point(data = occs, aes(x = .data[[lon_col]], y = .data[[lat_col]]),
             shape = 4, color = "black", size = 2, stroke = 0.8) +
  # Fix the aspect ratio to prevent horizontal stretching
  coord_sf(xlim = c(bbox_raster["xmin"], bbox_raster["xmax"]), 
           ylim = c(bbox_raster["ymin"], bbox_raster["ymax"]), 
           expand = FALSE) +
  # Styling
  theme_void() +
  theme(
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 12, margin = margin(b = 10)),
    legend.text = element_text(size = 10),
    legend.margin = margin(t = 0, r = 10, b = 0, l = 10),
    legend.key.width = unit(1.5, "cm"),
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    plot.margin = margin(10, 10, 10, 10)
  )

ggsave("o5_final_map_countries_fixed.png", plot = p, width = 8, height = 8, dpi = 300, bg = "white")
message("Map with geopolitical borders and fixed coordinates saved successfully.")

