# ============================================================================
# Notebook: nod_workspace-inspection
# Language: R
# Key: nod_workspace-inspection
# Generated: 2026-08-06T15:18:18.313Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-08-06T14:58:25.349Z ───────────────────────────────────
# Locate figure generation code
# Propósito: Scan code directory to find specific scripts responsible for ecological figure generation.
# runtime: modal:sdm-r
# duration_ms: 1947

# List and search R/Python files in code/ for ecological figure generation patterns
files <- list.files("code", full.names = TRUE)
for (f in files) {
  lines <- readLines(f, warn = FALSE)
  if (any(grepl("environmental_tolerance", lines))) {
    message(paste("Found 'environmental_tolerance' in:", f))
  }
  if (any(grepl("response_curves", lines))) {
    message(paste("Found 'response_curves' in:", f))
  }
}


# ──── #2 · Ejecución · 2026-08-06T15:06:31.945Z ───────────────────────────────────
# Grep environmental tolerance code
# Propósito: Locate environmental tolerance figure code in notebook_nod_general.R to restore it.
# Artifacts: #3863, #3866, #3861, #3862, #3865, #3864, #3867, #3868, #3869, #3870, #3873, #3871, #3872, #3874, #3877, #3875, #3876, #3878, #3880, #3879, #3881, #3882, #3883, #3887, #3884, #3885, #3886, #3888, #3889, #3890, #3891, #3892, #3893, #3894, #3895, #3896, #3897, #3898, #3899, #3900, #3901, #3902, #3903
# runtime: modal:sdm-r
# duration_ms: 2792

# Read and grep the specific lines for environmental_tolerance in notebook_nod_general.R
lines <- readLines("code/notebook_nod_general.R")
match_idx <- which(grepl("environmental_tolerance", lines))
if (length(match_idx) > 0) {
  # print the context around each match (15 lines before and after)
  for (idx in match_idx) {
    start <- max(1, idx - 10)
    end <- min(length(lines), idx + 25)
    cat(sprintf("--- Context around line %d ---\n", idx))
    cat(paste(lines[start:end], collapse="\n"), "\n\n")
  }
} else {
  cat("No match found for 'environmental_tolerance' in code/notebook_nod_general.R\n")
}


# ──── #3 · Ejecución · 2026-08-06T15:07:30.831Z ───────────────────────────────────
# Grep environmental tolerance in home directory
# Propósito: Locate environmental tolerance figure code in R scripts in the home directory.
# runtime: modal:sdm-r
# duration_ms: 2737

# Scan for environmental_tolerance in the home directory files
files <- list.files("/home/user", pattern = "\\.[rR]$", full.names = TRUE)
for (f in files) {
  lines <- readLines(f, warn = FALSE)
  if (any(grepl("environmental_tolerance", lines))) {
    message(paste("Found 'environmental_tolerance' in:", f))
    match_idx <- which(grepl("environmental_tolerance", lines))
    for (idx in match_idx) {
      start <- max(1, idx - 10)
      end <- min(length(lines), idx + 25)
      cat(sprintf("--- Context around line %d in %s ---\n", idx, basename(f)))
      cat(paste(lines[start:end], collapse="\n"), "\n\n")
    }
  }
}


# ──── #4 · Ejecución · 2026-08-06T15:08:44.655Z ───────────────────────────────────
# List root workspace files
# Propósito: List non-recursive files in the sandbox root to inspect direct workspace contents.
# runtime: modal:sdm-r
# duration_ms: 2651

# List files non-recursively in /home/user
files <- list.files("/home/user")
print(files)


# ──── #5 · Ejecución · 2026-08-06T15:09:34.446Z ───────────────────────────────────
# Check code folder existence
# Propósito: Check for the existence and contents of the code folder.
# runtime: modal:sdm-r
# duration_ms: 2670

# Check if the "code" folder exists in the workspace
cat("Does 'code' folder exist?:", dir.exists("code"), "\n")
if (dir.exists("code")) {
  print(list.files("code"))
}


# ──── #6 · Ejecución · 2026-08-06T15:15:06.712Z ───────────────────────────────────
# Scan log on sdm-r container
# Propósito: Scan execution log on active sdm-r container to extract code for the run ID.
# runtime: modal:sdm-r
# duration_ms: 2794

# Check if the execution log exists and grep the code
log_path <- "execution-logs/execution-log.jsonl"
cat("Does log exist?:", file.exists(log_path), "\n")
if (file.exists(log_path)) {
  con <- file(log_path, "r")
  while (TRUE) {
    line <- readLines(con, n = 1, warn = FALSE)
    if (length(line) == 0) break
    if (grepl("fast-chat-run-1785563873305-ar0n71", line)) {
      cat("Found the run! Line length:", nchar(line), "\n")
      # Let's save the line to a temporary file so we can inspect it or parse it
      writeLines(line, "temp_run_log.json")
      break
    }
  }
  close(con)
}


# ──── #7 · Ejecución · 2026-08-06T15:18:18.185Z ───────────────────────────────────
# Read external inputs manifest
# Propósito: Inspect external inputs manifest structure.
# runtime: modal:sdm-r
# duration_ms: 3219

# Read the local external_inputs_manifest.json file
if (file.exists("external_inputs_manifest.json")) {
  lines <- readLines("external_inputs_manifest.json", warn = FALSE)
  cat(paste(lines, collapse="\n"), "\n")
} else {
  cat("external_inputs_manifest.json does not exist.\n")
}

