# ============================================================================
# Notebook: nod_workspace-inspection
# Language: Python
# Key: nod_workspace-inspection
# Generated: 2026-08-06T15:11:26.685Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-08-06T15:11:26.564Z ───────────────────────────────────
# Extract code from execution log
# Propósito: Read specific log file directly to extract original R code.
# runtime: e2b:biostats-python
# duration_ms: 398

import json
import os

log_path = "execution-logs/execution-log.jsonl"
if os.path.exists(log_path):
    with open(log_path, 'r', encoding='utf-8') as f:
        for line in f:
            if "fast-chat-run-1785563873305-ar0n71" in line:
                try:
                    data = json.loads(line)
                    print("=== Found Code ===")
                    print(data.get("code", {}).get("content", "No code content found"))
                except Exception as e:
                    print(f"Error parsing line: {e}")
                break
else:
    print(f"Log path {log_path} does not exist.")

