# ============================================================================
# Notebook: o3_generate-final-categorized-map
# Language: Python
# Key: o3_generate-final-categorized-map
# Generated: 2026-08-05T22:37:46.767Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-08-05T22:36:04.783Z ───────────────────────────────────
# Combine final maps into single figure (Python fallback)
# Propósito: Combine binary and logistic maps side-by-side with A and B labels using matplotlib.
# error: [Errno 2] No such file or directory: 'o3_final_map_binary_eng.png'
# failed: true
# runtime: e2b:biostats-python
# duration_ms: 110

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Load images
img_A = mpimg.imread("o3_final_map_binary_eng.png")
img_B = mpimg.imread("o3_final_map_logistic_eng.png")

# Create figure with 2 subplots side-by-side
# We use a large figsize to preserve the high resolution of your maps
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 12), gridspec_kw={'wspace': 0.02, 'hspace': 0})

# Plot A (Binary)
ax1.imshow(img_A)
ax1.axis('off')
# Add bold "A" in top-left corner
ax1.text(0.02, 0.98, 'A', transform=ax1.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

# Plot B (Logistic)
ax2.imshow(img_B)
ax2.axis('off')
# Add bold "B" in top-left corner
ax2.text(0.02, 0.98, 'B', transform=ax2.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

# Save exactly as requested
plt.savefig("o3_combined_maps_AB.png", dpi=300, bbox_inches='tight', pad_inches=0.1, facecolor='white')
print("Combined figure successfully generated.")


# ──── #2 · Ejecución · 2026-08-05T22:36:42.349Z ───────────────────────────────────
# Combine final maps into single figure (Python fallback)
# Propósito: Combine binary and logistic maps side-by-side with A and B labels using matplotlib.
# error: invalid syntax (1662985837.py, line 178)
# failed: true
# runtime: e2b:biostats-python
# duration_ms: 105

# Cargar los paquetes necesarios para la manipulación de gráficos
library(ggplot2)
library(patchwork)

# Los pasos anteriores guardaron los objetos de gráfico ggplot como archivos .rds.
# El script de Python falló porque intentó cargar archivos .png que nunca se crearon.
# El enfoque correcto es cargar los objetos R y combinarlos usando un paquete de R como patchwork.

# Cargar los objetos de gráfico ggplot desde los archivos .rds
# Estos archivos fueron creados y verificados en pasos anteriores.
p_binary <- readRDS("p_binary.rds")
p_logistic <- readRDS("p_logistic.rds")

# Combinar los gráficos uno al lado del otro usando el operador '+' de patchwork.
# plot_annotation() agrega las etiquetas 'A' y 'B' en la esquina superior izquierda de cada gráfico.
# El '& theme(...)' aplica el estilo a las etiquetas de ambos subgráficos.
combined_plot <- (p_binary) + (p_logistic) +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 30, face = "bold"))

# Guardar el gráfico combinado en un archivo PNG.
# Se utilizan dimensiones y DPI similares a los del script de Python original para mantener la consistencia.
ggsave(
  "o3_combined_maps_AB.png",
  plot = combined_plot,
  width = 24,
  height = 12,
  units = "in",
  dpi = 300,
  bg = "white"
)

print("Combined figure successfully generated.")


# ──── #3 · Ejecución · 2026-08-05T22:37:11.820Z ───────────────────────────────────
# Combine final maps into single figure (Logical paths)
# Propósito: Combine maps reading from logical paths.
# error: Cannot find figures/o3_final_map_binary_eng.png
# failed: true
# runtime: e2b:biostats-python
# duration_ms: 93

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import shutil

path_A = "/workspace/figures/o3_final_map_binary_eng.png"
path_B = "/workspace/figures/o3_final_map_logistic_eng.png"

if not os.path.exists(path_A):
    # Try another location if /workspace/figures doesn't work
    path_A = "figures/o3_final_map_binary_eng.png"
    path_B = "figures/o3_final_map_logistic_eng.png"

if not os.path.exists(path_A):
    raise FileNotFoundError(f"Cannot find {path_A}")

img_A = mpimg.imread(path_A)
img_B = mpimg.imread(path_B)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 12), gridspec_kw={'wspace': 0.02, 'hspace': 0})

ax1.imshow(img_A)
ax1.axis('off')
ax1.text(0.02, 0.98, 'A', transform=ax1.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

ax2.imshow(img_B)
ax2.axis('off')
ax2.text(0.02, 0.98, 'B', transform=ax2.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

plt.savefig("o3_combined_maps_AB.png", dpi=300, bbox_inches='tight', pad_inches=0.1, facecolor='white')
print("Combined figure successfully generated.")


# ──── #4 · Ejecución · 2026-08-05T22:37:46.567Z ───────────────────────────────────
# Combine final maps into single figure (Logical paths)
# Propósito: Combine maps reading from logical paths.
# runtime: e2b:biostats-python
# duration_ms: 95
# failed: true
# error: Cannot find o3_final_map_binary_eng.png

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import shutil

# Corrected paths to look for the images in the current working directory,
# as the 'figures' subdirectory does not exist in the sandbox environment.
path_A = "o3_final_map_binary_eng.png"
path_B = "o3_final_map_logistic_eng.png"

if not os.path.exists(path_A):
    raise FileNotFoundError(f"Cannot find {path_A}")

if not os.path.exists(path_B):
    raise FileNotFoundError(f"Cannot find {path_B}")

img_A = mpimg.imread(path_A)
img_B = mpimg.imread(path_B)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 12), gridspec_kw={'wspace': 0.02, 'hspace': 0})

ax1.imshow(img_A)
ax1.axis('off')
ax1.text(0.02, 0.98, 'A', transform=ax1.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

ax2.imshow(img_B)
ax2.axis('off')
ax2.text(0.02, 0.98, 'B', transform=ax2.transAxes, fontsize=60, fontweight='bold', va='top', ha='left')

plt.savefig("o3_combined_maps_AB.png", dpi=300, bbox_inches='tight', pad_inches=0.1, facecolor='white')
print("Combined figure successfully generated.")

